#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motor3,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motor4,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
bool go=false;


float exponentialJoystick(int joyVal){
	return (float)pow((joyVal/12),2);
}

void joystickControllerOne()
{
	nxtDisplayCenteredBigTextLine(1,"%f",joystick.joy1_x2);
	if(go)
		motor[motor3]=37;
	else
		motor[motor3]=0;
	if(joy1Btn(1))
		go=!go;
	while(joy1Btn(1))
	{}

	if(joystick.joy1_x1>20&&joystick.joy1_x1>joystick.joy1_y1)
	{
		motor[motorRight] = joystick.joy1_x1;
		motor[motorLeft] = joystick.joy1_x1;
	}else if(joystick.joy1_x1<-20&&joystick.joy1_x1<joystick.joy1_y1)
	{
		motor[motorRight] = joystick.joy1_x1;
		motor[motorLeft] = joystick.joy1_x1;
	}
	else 	if(joystick.joy1_y1>10&&joystick.joy1_x1<joystick.joy1_y1)
	{
		motor[motorRight] = -joystick.joy1_y1;
		motor[motorLeft] = joystick.joy1_y1;
	}else if(joystick.joy1_y1<-10&&joystick.joy1_x1>joystick.joy1_y1)
	{
		motor[motorRight] = -joystick.joy1_y1;
		motor[motorLeft] = joystick.joy1_y1;
		}else{

		motor[motorRight] = 0;
		motor[motorLeft] = 0;
	}
}


task main(){
	waitForStart();
	ClearTimer(T1);
	while(true){
		joystickControllerOne();
		//joystickControllerTwo();
	}
}
