#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     armR,          tmotorTetrix, openLoop, encoder,reversed)
#pragma config(Motor,  mtr_S1_C2_2,     ramp,          tmotorTetrix, openLoop, encoder, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
#pragma config(Sensor, S4,     HTSMUX,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "/hitechnic-sensormux.h"
#include "/lego-ultrasound.h"
#include "/lego-light.h"
#include "/hitechnic-force.h"
#include "/hitechnic-irseeker-v2.h"
// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

// Give the sensor a nice easy to use namez
const tMUXSensor HTFS1 = msensor_S4_3;
const tMUXSensor HTFS2 = msensor_S4_2;
const tMUXSensor HTIRS2 = msensor_S4_1;
const tMUXSensor LEGOLS = msensor_S4_4;

int power,fs1,fs2,servoPos,col1,col2,col3,
	dcS1,dcS2,dcS3,dcS4,dcS5,acS1,acS2,acS3,
	acS4,acS5,bottomRow=10,middleRow=1500,lsVal;

/////////////////////////////////Arm Functions///////////////////////////////////
void raiseArm(int powerLevel){
	motor[armR]=powerLevel;
}

void lowerArm(int powerLevel){
	motor[armR]=-powerLevel;
}
/*
void botRow(){
	while(nMotorEncoder[armL]>
}*/

//////////////////////////////Movement Functions/////////////////////////////////
void forward(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = powerLevel;
}

void reverse(int powerLevel){
	motor[motorBL] = -powerLevel;
	motor[motorFL] = -powerLevel;
	motor[motorBR] = -powerLevel;
	motor[motorFR] = -powerLevel;
}

void right(int powerLevel){
	motor[motorBL] = 0;
	motor[motorFL] = 0;
	motor[motorBR] = powerLevel;
	motor[motorFR] = powerLevel;
}

void left(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = powerLevel;
	motor[motorBR] = 0;
	motor[motorFR] = 0;
}

void diagonalFR(int powerLevel){
	motor[motorBL] = 0;
	motor[motorFL] = powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = 0;
}


void rotateRight(int powerLevel){
	motor[motorBL] = -powerLevel;
	motor[motorFL] = -powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = powerLevel;
}

void rotateLeft(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = powerLevel;
	motor[motorBR] = -powerLevel;
	motor[motorFR] = -powerLevel;
}

void stop(){
	motor[motorBL] = 0;
	motor[motorFL] = 0;
	motor[motorBR] = 0;
	motor[motorFR] = 0;
	motor[armR] = 0;
	motor[ramp] = 0;
}



void init(){
	fs1 = fs2 = 0; //Force Sensor Values
	servoPos = 0; //Initiate Claw Servo Pos
	servo[servo1] = servoPos; //Set servo to servoPos
	nMotorEncoder[armR] = 0; //Initiate Encoder Pos
	servo[servo3]=35; //Initiate Servvo Ramp Lock
	power=50; //Motor Power Level
  LSsetActive(LEGOLS); //Turn on color sensor
  lsVal = LSvalNorm(LEGOLS);
	////Column positions left to right////
	col1=col2=col3=0;
}

task main()
{
	//Initiate Robot
	init();

	//Raise Arm
	while(nMotorEncoder[armR]<5){
		raiseArm(50);
		nxtDisplayCenteredTextLine(1,"Encoder:%i",nMotorEncoder[armR]);
	}
	stop();

  lsVal = LSvalNorm(LEGOLS);
	while(lsVal>85){
  	lsVal = LSvalNorm(LEGOLS);
		forward(10);
	}
	stop();
	wait1Msec(500);
	ClearTimer(T1);
	while(time1[T1]<1000){
		HTIRS2readAllDCStrength(HTIRS2,dcS1,dcS2,dcS3,dcS4,dcS5);
		HTIRS2readAllACStrength(HTIRS2, acS1, acS2, acS3, acS4, acS5);
		nxtDisplayCenteredTextLine(1,"IR:");
		nxtDisplayCenteredTextLine(2,"%i",acS1);
		nxtDisplayCenteredTextLine(3,"%i",acS2);
		nxtDisplayCenteredTextLine(4,"%i",acS3);
		nxtDisplayCenteredTextLine(5,"%i",acS4);
		nxtDisplayCenteredTextLine(6,"%i",acS5);
	}
	if(acS2<20&&acS4<20&&acS3>20)
		goto column2;
	else if(acS2>acS4)
		goto column3;
	else
		goto column1;

	////////First Column/////////////
	column1:;

	stop();

	nxtDisplayCenteredTextLine(1,"Column One:");nxtDisplayCenteredTextLine(2,"\n%i\n%i\n%i",acS2,acS3,acS4);
	////////Second Column/////////////
	column2:;
  lsVal = LSvalNorm(LEGOLS);
	while(time1[T1]<2000){
		if(lsVal<50){
			forward(15);
		}
		else{
			left(20);
		}
  	lsVal = LSvalNorm(LEGOLS);
	}
	stop();
	//forward(20);
	//wait1Msec(1000);
	//stop();
	//forward(30);
	//wait1Msec(250);
	//stop();

	while(true){nxtDisplayCenteredTextLine(1,"Column Two:");nxtDisplayCenteredTextLine(2,"\n%i\n%i\n%i",acS2,acS3,acS4);}
	////////Third Column//////////////
	column3:;

	stop();

	while(true){nxtDisplayCenteredTextLine(1,"Column Three:");nxtDisplayCenteredTextLine(2,"\n%i\n%i\n%i",acS2,acS3,acS4);}
}
