#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_2,     motorBL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_1,     motorFL,       tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorFR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorBR,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     armR,          tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     armL,          tmotorTetrix, openLoop, encoder, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoStandard)
#pragma config(Sensor, S2,     lightSensor,            sensorLightActive)
#pragma config(Sensor, S3,     HTIRS,               sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     HTSMUX,              sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "/hitechnic-sensormux.h"
#include "/lego-ultrasound.h"
#include "/lego-light.h"
#include "/hitechnic-force.h"
#include "/hitechnic-irseeker-v2.h"
// The sensor is connected to the first port
// of the SMUX which is connected to the NXT port S1.
// To access that sensor, we must use msensor_S1_1.  If the sensor
// were connected to 3rd port of the SMUX connected to the NXT port S4,
// we would use msensor_S4_3

// Give the sensor a nice easy to use name
//const tMUXSensor HTFS1 = msensor_S4_1;
//const tMUXSensor HTFS2 = msensor_S4_2;
const tMUXSensor LEGOUS = msensor_S4_3;
const int threshold = 20; //Controller Input Threshold
const int lsThreshold = 35;

//Global Variables
bool foundIR;
int dcS1,dcS2,dcS3,dcS4,dcS5;
int servoPos;
int dist;

//////////////////////////////Movement Functions/////////////////////////////////
void forward(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = powerLevel;
}

void reverse(int powerLevel){
	motor[motorBL] = -powerLevel;
	motor[motorFL] = -powerLevel;
	motor[motorBR] = -powerLevel;
	motor[motorFR] = -powerLevel;
}

void right(int powerLevel){
	motor[motorBL] = -powerLevel;
	motor[motorFL] = powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = -powerLevel;
}

void left(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = -powerLevel;
	motor[motorBR] = -powerLevel;
	motor[motorFR] = powerLevel;
}

void diagonalFR(int powerLevel){
	motor[motorBL] = 0;
	motor[motorFL] = powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = 0;
}

void diagonalBL(int powerLevel){
	motor[motorBL] = 0;
	motor[motorFL] = -powerLevel;
	motor[motorBR] = -powerLevel;
	motor[motorFR] = 0;
}

void diagonalFL(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = 0;
	motor[motorBR] = 0;
	motor[motorFR] = powerLevel;
}

void diagonalBR(int powerLevel){
	motor[motorBL] = -powerLevel;
	motor[motorFL] = 0;
	motor[motorBR] = 0;
	motor[motorFR] = -powerLevel;
}

void rotateRight(int powerLevel){
	motor[motorBL] = powerLevel;
	motor[motorFL] = powerLevel;
	motor[motorBR] = -powerLevel;
	motor[motorFR] = -powerLevel;
}

void rotateLeft(int powerLevel){
	motor[motorBL] = -powerLevel;
	motor[motorFL] = -powerLevel;
	motor[motorBR] = powerLevel;
	motor[motorFR] = powerLevel;
}

void stop(){
	motor[motorBL] = 0;
	motor[motorFL] = 0;
	motor[motorBR] = 0;
	motor[motorFR] = 0;
	motor[armL] = 0;
}

/////////////////////////////////Arm Control Functions///////////////////////////
void raiseArm(int powerLevel){
	motor[armL] = powerLevel;
}

void lowerArm(int powerLevel){
	motor[armL] = -powerLevel;
}

////////////////////////////////Claw Control Functions///////////////////////////
void setPos(int pos){
	servo[servo1] = pos;
}


////////////////////////////////Check IR Values/////////////////////////////////
void checkIR(){
	HTIRS2readAllDCStrength(HTIRS, dcS1, dcS2, dcS3, dcS4, dcS5); //Take IR reading
	if(dcS3>10){
		foundIR=true;
	}
}

void init(){
	servoPos = 0; //Initiate Claw Servo Pos
	foundIR=false;
	servo[servo1] = servoPos; //Set servo to servoPos
	nMotorEncoder[armR] = 0; //Initiate Encoder Pos
}

task main()
{
	init();

	waitForStart();

	while(SensorValue[lightSensor]<lsThreshold){ //Get onto board
		forward(100);
		nxtDisplayCenteredTextLine(1,"LS:%i",SensorValue[lightSensor]);
	}

	stop();

	while(SensorValue[lightSensor]<lsThreshold){ //Check middle column
		diagonalBL(50);
	}

	stop();

  checkIR();

	while(SensorValue[lightSensor]<lsThreshold&&!foundIR){ //Check left column
		diagonalBR(75);
	}

	stop();

	checkIR();

  while(SensorValue[lightSensor]<lsThreshold&&!foundIR){ //Check left column again
  	diagonalFL(100);
  }

  stop();

  checkIR();

  while(SensorValue[lightSensor]<lsThreshold&&!foundIR){ //Check middle column again
  	diagonalFL(50);
  }

  stop();

  checkIR();

  while(SensorValue[lightSensor]<lsThreshold&&!foundIR){ //Check right column
  	diagonalFL(50);
  }

  stop();

  checkIR();

  if(foundIR){
  	rotateRight(50);
  	wait1Msec(1000);
  	stop();
  	while(nMotorEncoder[armR]<1500){
  		raiseArm(50);
  	}

  	stop();

  	right(50);
  	wait1Msec(1500);

  	stop();

  	rotateLeft(50);
  	wait1Msec(1000);

  	stop();

	  dist = USreadDist(LEGOUS);
  	while(dist>20){
	   	dist = USreadDist(LEGOUS);
  		forward(20);
  	}

  	stop();

  	servo[servo1] = 225;
  	wait1Msec(500);

  	reverse(50);
  	wait1Msec(1000);

  	stop();
	}
}
